#Enable Gold Upgraded Totem Effect : Reduce Damage ?
EnableDamageBonusGoldWeapon = true
#By how much is the damage reduced in percentage ?
#Range: 1 ~ 100
DamageBonusGoldWeapon = 10
#Enable Fire Upgraded Totem Effect : Reduce Damage ?
EnableDamageBonusFireWeapon = true
#By how much is the damage reduced in percentage ?
#Range: 1 ~ 100
DamageBonusFireWeapon = 10
#Enable Ender Upgraded Totem Effect : Reduce Damage ?
EnableDamageBonusEnderWeapon = true
#By how much is the damage reduced in percentage ?
#Range: 1 ~ 100
DamageBonusEnderWeapon = 10
#Enable Water Upgraded Totem Effect : Reduce Damage ?
EnableDamageBonusWaterWeapon = true
#By how much is the damage reduced in percentage ?
#Range: 1 ~ 100
DamageBonusWaterWeapon = 10
#Enable Wither Upgraded Totem Effect : Reduce Damage ?
EnableDamageBonusWitherWeapon = true
#By how much is the damage reduced in percentage ?
#Range: 1 ~ 100
DamageBonusWitherWeapon = 10
#Enable Poison Upgraded Totem Effect : Reduce Damage ?
EnableDamageBonusPoisonWeapon = true
#By how much is the damage reduced in percentage ?
#Range: 1 ~ 100
DamageBonusPoisonWeapon = 10
#Enable Phantom Upgraded Totem Effect : Reduce Damage ?
EnableDamageBonusPhantomWeapon = true
#By how much is the damage reduced in percentage ?
#Range: 1 ~ 100
DamageBonusPhantomWeapon = 10
#Enable Feather Upgraded Totem Effect : Reduce Damage ?
EnableDamageBonusFeatherWeapon = true
#By how much is the damage reduced in percentage ?
#Range: 1 ~ 100
DamageBonusFeatherWeapon = 10
#Enable Corrupt Upgraded Totem Effect : Reduce Damage ?
EnableDamageBonusCorruptWeapon = true
#By how much is the damage reduced in percentage ?
#Range: 1 ~ 100
DamageBonusCorruptWeapon = 5

